-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocms that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
